CREATE TABLE "users" (
  	"id" SERIAL PRIMARY KEY,
  	"name" TEXT NOT NULL,
	"email" TEXT UNIQUE NOT NULL,
	"password" TEXT NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "urls" (
  	"id" SERIAL PRIMARY KEY,
  	"originalUrl" TEXT UNIQUE NOT NULL,
	"shortUrl" TEXT UNIQUE NOT NULL,
	"userId" INTEGER NOT NULL,
	"visitCount" INTEGER NOT NULL DEFAULT 0,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "sessions" (
  	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER UNIQUE NOT NULL,
	"token" TEXT UNIQUE NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);